name: identity-api

services:
  identity-db:
    image: postgres:18.4-alpine
    container_name: identity-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-identity_db}
      POSTGRES_USER: ${POSTGRES_USER:-identity_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-identity_local_password}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - identity_postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  identity_postgres_data: